### ISSUE TITLE
use of internal package

### ISSUE THREAD

**Issue by wolfgangmeyers** [favclip/testerator#1]
Any progress on resolving this? Is it possible to work around the internal package issue?

```
$ go get github.com/favclip/testerator
package github.com/favclip/testerator
	imports google.golang.org/appengine/internal/search: use of internal package not allowed
```

**Comment by wolfgangmeyers** [comment]
Also, have you considered creating a pull request to the main codebase?

**Comment by vvakame** [comment]
thank you for your comment. we've missed this issue.
Unfortunately, we don't have good ideas for this issue.
testerator have to remove all Search API document. but appengine sdk does not provide something like `search.GetAllIndex(c)` api... :cry: 
https://github.com/favclip/testerator/blob/d90ba6cd2ae52b36d44aef1e69e0c6d6ffe8d688/testarator.go#L192-L195
because, we are forced to use `appengine.WithAPICallFunc` and cast to `searchpb.IndexDocumentRequest`. it is struct of internal package. :sob: 

do you know any good solutions?

https://github.com/golang/appengine/blob/6a436539be38c296a8075a871cc536686b458371/search/search.go#L8
https://code.google.com/p/googleappengine/issues/detail?id=12417

**Comment by vvakame** [comment]
I made a new issue. https://code.google.com/p/googleappengine/issues/detail?id=12747

**Comment by vvakame** [comment]
It solved on master/HEAD.

please add below import statement 

```
	_ "github.com/favclip/testerator/datastore"
	_ "github.com/favclip/testerator/memcache"
	_ "github.com/favclip/testerator/search"
```
